services:
  frontend:
    image: davide92/react-example2
    container_name: frontend
  proxy:
    image: davide92/reverse-proxy
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    # TODO substitute with a proper /alive endpoint
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://raspberrypi:8080/translations/en" ]
      interval: 5s
      timeout: 3s
      retries: 3